import { Component, HostListener } from '@angular/core';
import { Router } from '@angular/router';
import { WorkOption } from '../../shared/model';

@Component({
  selector: 'app-photos',
  standalone: false,
  templateUrl: './photos.component.html',
})
export class PhotosComponent {
  downOption = WorkOption.Videos;
  prefix =
    'https://client-uploads-877b7177.s3.us-east-2.amazonaws.com/71db65b0-7081-7071-3f6f-b386c234050f/photos/';
  images = [
    `${this.prefix}Artboard_2_copy_3_wtwj1r.jpg`,
    `${this.prefix}IMG_8103_d81znk.jpg`,
    `${this.prefix}Scan_6_copy_xmydtb.jpg`,
    `${this.prefix}Scan_4_copy_jd4yrs.jpg`,
    `${this.prefix}IMG_0322_sa98o9.jpg`,
    `${this.prefix}IMG_8096_bm5sy3.jpg`,
    `${this.prefix}Artboard_1_copy_3_ea5u4d.jpg`,
    `${this.prefix}muchalucha_2_copy_2_gr5ny1.jpg`,
    `${this.prefix}hayley_2_i1zaes.jpg`,
    `${this.prefix}Scan_4_ghwdgh.jpg`,
    `${this.prefix}IMG_8105_opx5kp.jpg`,
    `${this.prefix}IMG_9008_jw7fck.jpg`,
    `${this.prefix}Scan_5_qn7tgz.jpg`,
    `${this.prefix}IMG_9982_hh5tiu.jpg`,
    `${this.prefix}hayley_3_copy_dpa6zj.jpg`,
    `${this.prefix}IMG_9338_goiyqr.jpg`,
    `${this.prefix}hayley_copy_jux3vf.jpg`,
    `${this.prefix}IMG_2478_vob0yb.jpg`,
    `${this.prefix}muchalucha_1_copy_oltocq.jpg`,
    `${this.prefix}Artboard_3_copy_3_z1okwv.jpg`,
    `${this.prefix}muchalucha_copy_ozqfzy.jpg`,
    `${this.prefix}Artboard_3_copy_2_bjoblq.jpg`,
    `${this.prefix}IMG_9314_oyoac6.jpg`,
    `${this.prefix}IMG_9988_n665ct.jpg`,
    `${this.prefix}IMG_8100_bgoobt.jpg`,
    `${this.prefix}muchalucha_3_copy_crsbk1.jpg`,
    `${this.prefix}IMG_9014_alyyrt.jpg`,
    `${this.prefix}Artboard_1_copy_3_d39lt7.jpg`,
    `${this.prefix}IMG_8095_xtldzd.jpg`,
    `${this.prefix}Artboard_1_copy_2_e6k0wy.jpg`,
    `${this.prefix}IMG_9007_xhvalb.jpg`,
    `${this.prefix}IMG_2479_oenzdq.jpg`,
    `${this.prefix}IMG_9986_k1ymwz.jpg`,
    `${this.prefix}IMG_0679_pkwljh.jpg`,
  ];
}

/**
[
...     '${prefix}Artboard_1_copy_3_ea5u4d.jpg',
...     '${prefix}muchalucha_copy_ozqfzy.jpg',
...     '${prefix}muchalucha_2_copy_2_gr5ny1.jpg',
...     '${prefix}IMG_2478_vob0yb.jpg',
...     '${prefix}Scan_4_ghwdgh.jpg',
...     '${prefix}muchalucha_1_copy_oltocq.jpg',
...     '${prefix}IMG_9982_hh5tiu.jpg',
...     '${prefix}IMG_9314_oyoac6.jpg',
...     '${prefix}muchalucha_3_copy_crsbk1.jpg',
...     '${prefix}IMG_8100_bgoobt.jpg',
...     // DEL IN S3 '${prefix}IMG_9550_f7qqvc.jpg',
...     '${prefix}IMG_9007_xhvalb.jpg',
...     // DEL IN S3 '${prefix}Artboard_4_copy_akpm1k.jpg',
...     '${prefix}IMG_8103_d81znk.jpg',
...     '${prefix}Artboard_3_copy_2_bjoblq.jpg',
...     // DEL IN S3 '${prefix}IMG_0337_hnrv9u.jpg',
...     '${prefix}hayley_2_i1zaes.jpg',
...     '${prefix}Scan_4_copy_jd4yrs.jpg',
...     '${prefix}IMG_9008_jw7fck.jpg',
...     // todo accidentally deleted '${prefix}Artboard_2_copy_2_fxnflr.jpg',
...     // DEL IN S3 '${prefix}IMG_0633_wbehzb.jpg',
...     // DEL IN S3 '${prefix}IMG_0339_afyvj9.jpg',
...     // DEL IN S3 '${prefix}Artboard_8_copy_dlaup4.jpg',
...     // DEL IN S3 '${prefix}Artboard_5_copy_vhbfwx.jpg',
...     '${prefix}Artboard_1_copy_3_d39lt7.jpg',
...     // DEL IN S3 '${prefix}IMG_9569_jbvhyk.jpg',
...     '${prefix}Artboard_1_copy_2_e6k0wy.jpg',
...     // DEL IN S3 '${prefix}IMG_0332_m15w87.jpg',
...     '${prefix}Scan_5_qn7tgz.jpg',
...     '${prefix}Artboard_3_copy_3_z1okwv.jpg',
...     // DEL IN S3 '${prefix}IMG_0654_xqvlau.jpg',
...     '${prefix}IMG_8095_xtldzd.jpg',
...     '${prefix}IMG_9986_k1ymwz.jpg',
...     '${prefix}Artboard_2_copy_3_wtwj1r.jpg',
...     '${prefix}hayley_copy_jux3vf.jpg',
...     // DEL IN S3 '${prefix}IMG_9738_2_x6gijj.jpg',
...     '${prefix}IMG_0679_pkwljh.jpg',
...     '${prefix}IMG_8105_opx5kp.jpg',
...     '${prefix}Scan_6_copy_xmydtb.jpg',
...     '${prefix}IMG_9014_alyyrt.jpg',
...     '${prefix}IMG_0322_sa98o9.jpg',
...     // '${prefix}Artboard_4_bafcwx.jpg',
...     '${prefix}IMG_9988_n665ct.jpg',
...     // '${prefix}Artboard_4_copy_2_sh5tuu.jpg',
...     '${prefix}IMG_8096_bm5sy3.jpg',
...     // DEL IN S3 '${prefix}IMG_0326_wgcffj.jpg',
...     '${prefix}IMG_2479_oenzdq.jpg',
...     // DEL IN S3 '${prefix}IMG_9319_d5nndj.jpg',
...     '${prefix}IMG_9338_goiyqr.jpg',
...     // DEL IN S3 '${prefix}IMG_9570_nw7xe9.jpg',
...     '${prefix}hayley_3_copy_dpa6zj.jpg',
...   ];
 */
